_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 12
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 16
                - 23
                - 38
                - 55
            "4": 3.12.4
            "5": 0.19.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
epochs:
    value: 5
loss_function:
    value: binary_crossentropy
metrics:
    value: accuracy
model:
    value: Bidirectional
optimizer:
    value: Adam
